apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-kargo-poc-app
  namespace: kargo-promotion
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc-app
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: env
              value: tst
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tst-kargo-poc-app
  namespace: kargo-promotion
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc-app
      sources:
        stages:
          - dev-kargo-poc-app
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: openpr
              value: "true"
            - name: env
              value: tst
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: acc-kargo-poc-app
  namespace: kargo-promotion
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc-app
      sources:
        stages:
          - tst-kargo-poc-app
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: openpr
              value: "true"
            - name: env
              value: acc
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prd-kargo-poc-app
  namespace: kargo-promotion
  annotations:
    kargo.akuity.io/color: black
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc-app
      sources:
        stages:
          - acc-kargo-poc-app
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: openpr
              value: "true"
            - name: env
              value: prd
